import type { Metadata, Viewport } from "next";
import { fontMono, fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import "@/app/globals.css";
import { Providers, ThemeProvider } from "@/providers/providers";

export const viewport: Viewport = {
	initialScale: 1,
	width: "device-width",
	maximumScale: 1,
};

export const metadata: Metadata = {
	title: "Relationship Meter",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang="en" suppressHydrationWarning={true}>
				<body suppressHydrationWarning={true} className={cn("w-full overflow-x-hidden h-svh font-sans antialiased bg-bg", fontSans.variable, fontMono.variable)}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</Providers>
	);
}
