import type { Relationship } from "@/types"

export const initialRelationships: Relationship[] = [
    { id: 1, name: "Mom", strength: 100, type: "family" },
    { id: 2, name: "John (Best Friend)", strength: 85, type: "friend" },
    { id: 3, name: "Sarah (Colleague)", strength: 70, type: "acquaintance" },
    { id: 4, name: "Partner", strength: 95, type: "significant_other" },
    { id: 5, name: "Dad", strength: 98, type: "family" },
    { id: 6, name: "Emily (Sister)", strength: 90, type: "family" },
    { id: 7, name: "David (Old Friend)", strength: 60, type: "friend" },
    { id: 8, name: "Michael (Gym Buddy)", strength: 50, type: "acquaintance" },
    { id: 9, name: "Jessica (Work Friend)", strength: 75, type: "colleague" },
    { id: 10, name: "Boss", strength: 65, type: "colleague" },
    { id: 11, name: "Neighbor (Mrs. Johnson)", strength: 40, type: "acquaintance" },
    { id: 12, name: "Uncle Bob", strength: 80, type: "family" },
    { id: 13, name: "Aunt Lisa", strength: 78, type: "family" },
    { id: 14, name: "Cousin Jake", strength: 55, type: "family" },
    { id: 15, name: "Tom (Gaming Buddy)", strength: 68, type: "friend" },
    { id: 16, name: "Sophia (Mentor)", strength: 88, type: "colleague" },
    { id: 17, name: "Liam (Online Friend)", strength: 45, type: "friend" },
    { id: 18, name: "Natalie (Study Partner)", strength: 72, type: "acquaintance" },
    { id: 19, name: "Grandma", strength: 95, type: "family" },
    { id: 20, name: "Grandpa", strength: 92, type: "family" },
    { id: 21, name: "Derek (Business Partner)", strength: 67, type: "colleague" },
    { id: 22, name: "Lucy (Childhood Friend)", strength: 79, type: "friend" },
    { id: 23, name: "Anna (Yoga Classmate)", strength: 48, type: "acquaintance" },
    { id: 24, name: "Ethan (Cousin)", strength: 58, type: "family" },
    { id: 25, name: "Olivia (Close Friend)", strength: 83, type: "friend" },
    { id: 26, name: "Ben (Distant Relative)", strength: 35, type: "family" },
    { id: 27, name: "Carl (Old Professor)", strength: 60, type: "acquaintance" },
    { id: 28, name: "Henry (Bartender)", strength: 30, type: "acquaintance" },
    { id: 29, name: "Zoey (Dog Walker)", strength: 40, type: "acquaintance" },
    { id: 30, name: "Rachel (Sister-in-law)", strength: 75, type: "family" },
  ];